AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 16

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
